#!/usr/bin/env python3
"""
Publication-grade plotting for the CollEdge paper.

Each figure is generated by an independent function that:
  1. Loads its own JSON file from --data-dir.
  2. Writes a self-contained PDF + PNG to --out-dir.
  3. Shares only a small `apply_style()` rcParams preset with the others.

This file can be copied verbatim into another folder; pass --data-dir to point
at the figure_data/ directory and --out-dir at the desired output location.

Usage
-----
    python plot_figures.py                   # use defaults next to this script
    python plot_figures.py --data-dir DIR --out-dir DIR
    python plot_figures.py --only fig1,fig4  # render a subset
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Iterable

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# ---------------------------------------------------------------------------
# Style
# ---------------------------------------------------------------------------

# Restrained, colour-blind friendly palette inspired by Tableau / ColorBrewer.
PALETTE = {
    "CollEdge":         "#d62728",   # red — our method, used sparingly
    "DCFCL":            "#9467bd",   # purple
    "FedAvg":           "#1f77b4",   # blue
    "FedProx":          "#17becf",   # teal
    "FedLwF":           "#2ca02c",   # green
    "SCAFFOLD":         "#bcbd22",   # olive
    "Per-FedAvg":       "#ff7f0e",   # orange
    "PerAvg":           "#ff7f0e",
    "pFedMe":           "#8c564b",   # brown
    "ClusterFL":        "#e377c2",   # pink
    "Local Only":       "#7f7f7f",   # grey
    "Local":            "#7f7f7f",
    # Ablation variants
    "DCFCL (Baseline)": "#7f7f7f",
    "+DER++":           "#1f77b4",
    "+DER++ +Directed": "#2ca02c",
    "+DER++ +Coalition":"#ff7f0e",
    "Directed only":    "#9467bd",
    "Coalition only":   "#17becf",
}

LINESTYLES = {
    "CollEdge":   "-",
    "DCFCL":      "--",
    "FedAvg":     "-",
    "FedProx":    "-.",
    "FedLwF":     ":",
    "SCAFFOLD":   "--",
    "Per-FedAvg": "-.",
    "PerAvg":     "-.",
    "pFedMe":     ":",
    "ClusterFL":  "--",
    "Local Only": ":",
    "Local":      ":",
}

MARKERS = {
    "CollEdge":   "o",
    "DCFCL":      "s",
    "FedAvg":     "^",
    "FedProx":    "D",
    "FedLwF":     "v",
    "SCAFFOLD":   "P",
    "Per-FedAvg": "*",
    "PerAvg":     "*",
    "pFedMe":     "X",
    "ClusterFL":  "h",
    "Local Only": "x",
    "Local":      "x",
}

DS_TITLES = {
    "EMNIST-Letters": "EMNIST-Letters",
    "CIFAR100":       "CIFAR-100",
}


def apply_style() -> None:
    """Single-source rcParams preset suited to IEEE / Nature double-column figures."""
    plt.rcParams.update(
        {
            # Fonts
            "font.family":      "serif",
            "font.serif":       ["Times New Roman", "Nimbus Roman", "DejaVu Serif"],
            "mathtext.fontset": "stix",
            "font.size":        9.0,
            "axes.titlesize":   10.0,
            "axes.labelsize":   9.5,
            "xtick.labelsize":  8.5,
            "ytick.labelsize":  8.5,
            "legend.fontsize":  8.0,
            "legend.title_fontsize": 8.5,
            # Lines / spines
            "axes.linewidth":   0.8,
            "lines.linewidth":  1.4,
            "xtick.major.width": 0.7,
            "ytick.major.width": 0.7,
            "xtick.direction":  "in",
            "ytick.direction":  "in",
            # Grid
            "axes.grid":        True,
            "grid.alpha":       0.25,
            "grid.linestyle":   "--",
            "grid.linewidth":   0.5,
            # Output
            "figure.dpi":       150,
            "savefig.dpi":      300,
            "savefig.bbox":     "tight",
            "pdf.fonttype":     42,   # editable text in vector PDFs
            "ps.fonttype":      42,
        }
    )


def style_for(name: str) -> dict:
    return dict(
        color=PALETTE.get(name, "#444444"),
        linestyle=LINESTYLES.get(name, "-"),
        marker=MARKERS.get(name, "."),
    )


# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------

def load(data_dir: Path, fname: str) -> dict:
    with open(data_dir / fname, "r") as f:
        return json.load(f)


def save(fig, out_dir: Path, name: str) -> None:
    pdf = out_dir / f"{name}.pdf"
    png = out_dir / f"{name}.png"
    fig.savefig(pdf)
    fig.savefig(png)
    plt.close(fig)
    print(f"[ok] {pdf.relative_to(pdf.parents[1])}")


# ---------------------------------------------------------------------------
# Figure 1 — Accuracy vs communication round (per dataset)
# ---------------------------------------------------------------------------

def plot_fig1(data_dir: Path, out_dir: Path) -> None:
    data = load(data_dir, "fig1_comm_rounds.json")
    fig, axes = plt.subplots(1, 2, figsize=(7.0, 2.8), sharey=False)

    for ax, ds in zip(axes, ["EMNIST-Letters", "CIFAR100"]):
        for algo, info in data[ds].items():
            name = info["display_name"]
            sty = style_for(name)
            mevery = max(1, len(info["rounds"]) // 10)
            ax.plot(
                info["rounds"], info["accuracy"],
                label=name,
                markevery=mevery, markersize=3.5, markerfacecolor="white",
                linewidth=1.8 if name == "CollEdge" else 1.0,
                zorder=10 if name == "CollEdge" else 4,
                **sty,
            )
        ax.set_title(DS_TITLES[ds])
        ax.set_xlabel("Communication round")
        ax.set_ylabel("Average accuracy (\\%)" if ax is axes[0] else "")
        # task boundary guides
        n_rounds = len(next(iter(data[ds].values()))["rounds"])
        n_tasks = 6 if ds == "EMNIST-Letters" else 10
        for t in range(1, n_tasks):
            ax.axvline(t * n_rounds // n_tasks, color="0.7",
                       linestyle=":", linewidth=0.6, zorder=1)

    # Single shared legend below the figure
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=5,
               frameon=False, bbox_to_anchor=(0.5, -0.05))
    fig.tight_layout(rect=[0, 0.04, 1, 1])
    save(fig, out_dir, "fig1_comm_rounds")


# ---------------------------------------------------------------------------
# Figure 2 — Forgetting heat-map (CollEdge vs FedAvg)
# ---------------------------------------------------------------------------

def plot_fig2(data_dir: Path, out_dir: Path) -> None:
    data = load(data_dir, "fig2_forgetting_staircase.json")
    targets = ["CollEdge", "FedAvg"]
    fig, axes = plt.subplots(2, 2, figsize=(7.0, 6.0))

    cmap = plt.cm.RdYlGn
    norm = plt.Normalize(0, 100)

    for r, ds in enumerate(["EMNIST-Letters", "CIFAR100"]):
        for c, algo in enumerate(targets):
            ax = axes[r, c]
            if algo not in data[ds]:
                ax.set_visible(False)
                continue
            info = data[ds][algo]
            n = info["n_tasks"]
            # The raw matrix is a staircase (row t has t+1 entries). Pad to n×n.
            raw = info["per_task_acc_matrix"]
            mat = np.full((n, n), np.nan, dtype=float)
            for t, row in enumerate(raw):
                for j, v in enumerate(row):
                    mat[t, j] = v

            disp = np.ma.array(mat, mask=np.isnan(mat))
            ax.imshow(disp, cmap=cmap, norm=norm, aspect="equal")

            for t in range(n):
                for j in range(t + 1):
                    if np.isnan(mat[t, j]):
                        continue
                    val = mat[t, j]
                    txt_color = "black" if 25 < val < 75 else "white"
                    ax.text(j, t, f"{val:.0f}", ha="center", va="center",
                            fontsize=6.5, color=txt_color)

            ax.set_xticks(range(n))
            ax.set_yticks(range(n))
            ax.set_xticklabels([f"T{i+1}" for i in range(n)])
            ax.set_yticklabels([f"after T{i+1}" for i in range(n)])
            ax.tick_params(length=0)
            ax.set_title(f"{DS_TITLES[ds]} — {algo}")
            if c == 0:
                ax.set_ylabel("Training stage")
            ax.set_xlabel("Test task")
            for s in ax.spines.values():
                s.set_visible(False)

    sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=axes.ravel().tolist(),
                        fraction=0.025, pad=0.02, shrink=0.85)
    cbar.set_label("Accuracy (\\%)", fontsize=8)
    cbar.ax.tick_params(labelsize=7)
    save(fig, out_dir, "fig2_forgetting_heatmap")


# ---------------------------------------------------------------------------
# Figure 3 — Aggregation effect (CollEdge vs Local vs FedAvg vs DCFCL)
# ---------------------------------------------------------------------------

def plot_fig3(data_dir: Path, out_dir: Path) -> None:
    data = load(data_dir, "fig3_aggregation_effect.json")
    fig, axes = plt.subplots(1, 2, figsize=(7.0, 2.8))

    for ax, ds in zip(axes, ["EMNIST-Letters", "CIFAR100"]):
        for algo, info in data[ds].items():
            name = info["display_name"]
            sty = style_for(name)
            ax.plot(info["rounds"], info["accuracy"], label=name,
                    linewidth=1.8 if name == "CollEdge" else 1.0,
                    zorder=10 if name == "CollEdge" else 4, **sty)
        ax.set_title(DS_TITLES[ds])
        ax.set_xlabel("Communication round")
        ax.set_ylabel("Average accuracy (\\%)" if ax is axes[0] else "")

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=4,
               frameon=False, bbox_to_anchor=(0.5, -0.04))
    fig.tight_layout(rect=[0, 0.04, 1, 1])
    save(fig, out_dir, "fig3_aggregation_effect")


# ---------------------------------------------------------------------------
# Figure 4 — Final per-task accuracy (emergence snapshot)
# ---------------------------------------------------------------------------

def plot_fig4(data_dir: Path, out_dir: Path) -> None:
    data = load(data_dir, "fig4_emergence.json")
    algos = ["CollEdge", "DCFCL", "FedAvg"]
    fig, axes = plt.subplots(1, 2, figsize=(7.0, 2.8))

    bw = 0.27
    for ax, ds in zip(axes, ["EMNIST-Letters", "CIFAR100"]):
        n = data[ds][algos[0]]["n_tasks"]
        x = np.arange(n)
        for i, algo in enumerate(algos):
            if algo not in data[ds]:
                continue
            vals = data[ds][algo]["final_per_task_acc"]
            ax.bar(x + (i - 1) * bw, vals, bw,
                   label=algo, color=PALETTE.get(algo),
                   edgecolor="white", linewidth=0.4)
        ax.set_xticks(x)
        ax.set_xticklabels([f"T{i+1}" for i in range(n)])
        ax.set_xlabel("Task index")
        ax.set_ylabel("Accuracy (\\%) at final round" if ax is axes[0] else "")
        ax.set_title(DS_TITLES[ds])
        ax.set_ylim(0, 100)

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=3,
               frameon=False, bbox_to_anchor=(0.5, -0.04))
    fig.tight_layout(rect=[0, 0.04, 1, 1])
    save(fig, out_dir, "fig4_emergence")


# ---------------------------------------------------------------------------
# Figure 5 — Past-task retention timeline
# ---------------------------------------------------------------------------

def plot_fig5(data_dir: Path, out_dir: Path) -> None:
    data = load(data_dir, "fig4_emergence.json")
    algos = ["CollEdge", "DCFCL", "FedAvg"]
    fig, axes = plt.subplots(1, 2, figsize=(7.0, 2.8))

    for ax, ds in zip(axes, ["EMNIST-Letters", "CIFAR100"]):
        for algo in algos:
            if algo not in data[ds]:
                continue
            info = data[ds][algo]
            past = info["past_avg_over_time"]
            stages = [i + 1 for i, v in enumerate(past) if v is not None]
            values = [v for v in past if v is not None]
            sty = style_for(algo)
            ax.plot(stages, values, label=algo,
                    linewidth=1.8 if algo == "CollEdge" else 1.0,
                    markersize=4, markerfacecolor="white",
                    zorder=10 if algo == "CollEdge" else 4, **sty)
        ax.set_title(DS_TITLES[ds])
        ax.set_xlabel("After learning task \\#")
        ax.set_ylabel("Avg.\\ acc.\\ on previous tasks (\\%)" if ax is axes[0] else "")
        n = data[ds][algos[0]]["n_tasks"]
        ax.set_xticks(range(1, n + 1))

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=3,
               frameon=False, bbox_to_anchor=(0.5, -0.04))
    fig.tight_layout(rect=[0, 0.04, 1, 1])
    save(fig, out_dir, "fig5_emergence_timeline")


# ---------------------------------------------------------------------------
# Figure 6 — Module ablation (horizontal bar)
# ---------------------------------------------------------------------------

def plot_fig6(data_dir: Path, out_dir: Path) -> None:
    rows = load(data_dir, "table4_ablation.json")
    rows_d = {r["variant"]: r for r in rows}
    order = [
        "DCFCL (Baseline)", "+DER++", "+DER++ +Directed",
        "+DER++ +Coalition", "CollEdge", "Directed only", "Coalition only",
    ]
    fig, axes = plt.subplots(1, 2, figsize=(7.0, 3.2), sharey=True)

    for ax, ds in zip(axes, ["EMNIST-Letters", "CIFAR100"]):
        key = f"{ds}_avg_acc"
        names, vals, cols = [], [], []
        for v in order:
            if v in rows_d and rows_d[v].get(key) is not None:
                names.append(v)
                vals.append(rows_d[v][key])
                cols.append(PALETTE.get(v, "#444"))
        y = np.arange(len(names))
        bars = ax.barh(y, vals, color=cols, edgecolor="white",
                       linewidth=0.4, height=0.65)
        for b, v in zip(bars, vals):
            ax.text(v + 0.6, b.get_y() + b.get_height() / 2,
                    f"{v:.1f}", va="center", ha="left", fontsize=7.5)
        ax.set_yticks(y)
        ax.set_yticklabels(names)
        ax.invert_yaxis()
        ax.set_xlabel("Average accuracy (\\%)")
        ax.set_title(DS_TITLES[ds])
        ax.set_xlim(0, max(vals) * 1.18)
        # bold our method's tick label
        for lbl in ax.get_yticklabels():
            if lbl.get_text() == "CollEdge":
                lbl.set_fontweight("bold")
                lbl.set_color(PALETTE["CollEdge"])

    fig.tight_layout()
    save(fig, out_dir, "fig6_ablation_bar")


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

REGISTRY = {
    "fig1": plot_fig1,
    "fig2": plot_fig2,
    "fig3": plot_fig3,
    "fig4": plot_fig4,
    "fig5": plot_fig5,
    "fig6": plot_fig6,
}


def main(argv: Iterable[str] | None = None) -> None:
    here = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", default=here / "figure_data",
                        type=Path, help="Directory with figureN.json files.")
    parser.add_argument("--out-dir",  default=here / "figures",
                        type=Path, help="Directory in which PDFs/PNGs are written.")
    parser.add_argument("--only", default="", type=str,
                        help="Comma-separated subset, e.g. 'fig1,fig4'.")
    args = parser.parse_args(argv)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    apply_style()

    selected = [s.strip() for s in args.only.split(",") if s.strip()] or list(REGISTRY)
    for key in selected:
        if key not in REGISTRY:
            raise SystemExit(f"unknown figure: {key}")
        REGISTRY[key](args.data_dir, args.out_dir)

    print(f"\nDone. Output → {args.out_dir}")


if __name__ == "__main__":
    main()
