#!/usr/bin/env python3
"""
Publication-grade plotting for the CollEdge paper.

Each figure is generated by an independent function that:
  1. Loads its own JSON file from --data-dir.
  2. Writes a self-contained PDF + PNG to --out-dir.
  3. Shares only a small `apply_style()` rcParams preset with the others.

This file can be copied verbatim into another folder; pass --data-dir to point
at the figure_data/ directory and --out-dir at the desired output location.

Usage
-----
    python plot_figures.py                   # use defaults next to this script
    python plot_figures.py --data-dir DIR --out-dir DIR
    python plot_figures.py --only fig1,fig4  # render a subset
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Iterable

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# ---------------------------------------------------------------------------
# Style
# ---------------------------------------------------------------------------

# Restrained, colour-blind friendly palette inspired by Tableau / ColorBrewer.
PALETTE = {
    "CollEdge":         "#d62728",   # red — our method, used sparingly
    "DCFCL":            "#9467bd",   # purple
    "FedAvg":           "#1f77b4",   # blue
    "FedProx":          "#17becf",   # teal
    "FedLwF":           "#2ca02c",   # green
    "SCAFFOLD":         "#bcbd22",   # olive
    "Per-FedAvg":       "#ff7f0e",   # orange
    "PerAvg":           "#ff7f0e",
    "pFedMe":           "#8c564b",   # brown
    "ClusterFL":        "#e377c2",   # pink
    "Local Only":       "#7f7f7f",   # grey
    "Local":            "#7f7f7f",
    # Ablation variants
    "DCFCL (Baseline)": "#7f7f7f",
    "+DER++":           "#1f77b4",
    "+DER++ +Directed": "#2ca02c",
    "+DER++ +Coalition":"#ff7f0e",
    "Directed only":    "#9467bd",
    "Coalition only":   "#17becf",
}

LINESTYLES = {
    "CollEdge":   "-",
    "DCFCL":      "--",
    "FedAvg":     "-",
    "FedProx":    "-.",
    "FedLwF":     ":",
    "SCAFFOLD":   "--",
    "Per-FedAvg": "-.",
    "PerAvg":     "-.",
    "pFedMe":     ":",
    "ClusterFL":  "--",
    "Local Only": ":",
    "Local":      ":",
}

MARKERS = {
    "CollEdge":   "o",
    "DCFCL":      "s",
    "FedAvg":     "^",
    "FedProx":    "D",
    "FedLwF":     "v",
    "SCAFFOLD":   "P",
    "Per-FedAvg": "*",
    "PerAvg":     "*",
    "pFedMe":     "X",
    "ClusterFL":  "h",
    "Local Only": "x",
    "Local":      "x",
}

DS_TITLES = {
    "EMNIST-Letters": "EMNIST-Letters",
    "CIFAR100":       "CIFAR-100",
}


def apply_style() -> None:
    """Single-source rcParams preset (Arial, Nature-style)."""
    plt.rcParams.update(
        {
            # Fonts — Arial everywhere
            "font.family":      "sans-serif",
            "font.sans-serif":  ["Arial", "Helvetica", "DejaVu Sans"],
            "mathtext.fontset": "custom",
            "mathtext.rm":      "Arial",
            "mathtext.it":      "Arial:italic",
            "mathtext.bf":      "Arial:bold",
            "font.size":        11.0,
            "axes.titlesize":   12.0,
            "axes.labelsize":   12.0,
            "xtick.labelsize":  10.5,
            "ytick.labelsize":  10.5,
            "legend.fontsize":  10.0,
            "legend.title_fontsize": 10.5,
            # Lines / spines (Nature-like: thin, no top/right)
            "axes.linewidth":   0.9,
            "lines.linewidth":  1.5,
            "axes.spines.top":   False,
            "axes.spines.right": False,
            "xtick.major.width": 0.9,
            "ytick.major.width": 0.9,
            "xtick.direction":  "out",
            "ytick.direction":  "out",
            "xtick.major.size": 3.0,
            "ytick.major.size": 3.0,
            # Grid (light, only y by default)
            "axes.grid":        False,
            "grid.alpha":       0.25,
            "grid.linestyle":   "-",
            "grid.linewidth":   0.4,
            # Output
            "figure.dpi":       150,
            "savefig.dpi":      300,
            "savefig.bbox":     "tight",
            "pdf.fonttype":     42,
            "ps.fonttype":      42,
        }
    )


def style_for(name: str) -> dict:
    return dict(
        color=PALETTE.get(name, "#444444"),
        linestyle=LINESTYLES.get(name, "-"),
        marker=MARKERS.get(name, "."),
    )


# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------

def load(data_dir: Path, fname: str) -> dict:
    with open(data_dir / fname, "r") as f:
        return json.load(f)


def save(fig, out_dir: Path, name: str) -> None:
    pdf = out_dir / f"{name}.pdf"
    png = out_dir / f"{name}.png"
    fig.savefig(pdf)
    fig.savefig(png)
    plt.close(fig)
    print(f"[ok] {pdf.relative_to(pdf.parents[1])}")


# ---------------------------------------------------------------------------
# Figure 1 — Accuracy vs communication round (vertically stacked, Nature-style)
# ---------------------------------------------------------------------------

# Algorithms excluded from all per-round figures (Per-FedAvg removed by request)
_EXCLUDE = {"PerAvg", "Per-FedAvg"}


def plot_fig1(data_dir: Path, out_dir: Path) -> None:
    data = load(data_dir, "fig1_comm_rounds.json")
    fig, axes = plt.subplots(2, 1, figsize=(7.0, 7.4), sharey=False)

    panel_labels = ["a", "b"]
    for ax, ds, plab in zip(axes, ["EMNIST-Letters", "CIFAR100"], panel_labels):
        for algo, info in data[ds].items():
            if algo in _EXCLUDE:
                continue
            name = info["display_name"]
            sty = style_for(name)
            mevery = max(1, len(info["rounds"]) // 12)
            ax.plot(
                info["rounds"], info["accuracy"],
                label=name,
                markevery=mevery, markersize=4.5, markerfacecolor="white",
                markeredgewidth=1.0,
                linewidth=2.2 if name == "CollEdge" else 1.2,
                zorder=10 if name == "CollEdge" else 4,
                **sty,
            )
        ax.set_xlabel("Communication round")
        ax.set_ylabel("Average accuracy (%)")
        ax.set_title(DS_TITLES[ds], loc="center", pad=6)
        # Nature-style panel label
        ax.text(-0.08, 1.02, plab, transform=ax.transAxes,
                fontsize=14, fontweight="bold", va="bottom", ha="right")
        # task boundary guides
        n_rounds = len(next(iter(data[ds].values()))["rounds"])
        n_tasks = 6 if ds == "EMNIST-Letters" else 10
        for t in range(1, n_tasks):
            ax.axvline(t * n_rounds // n_tasks, color="0.75",
                       linestyle=":", linewidth=0.6, zorder=1)
        ax.margins(x=0.01)
        ax.tick_params(top=False, right=False)

    # Single shared legend below the figure
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=4,
               frameon=False, bbox_to_anchor=(0.5, -0.02))
    fig.tight_layout(rect=[0, 0.05, 1, 1])
    save(fig, out_dir, "fig1_comm_rounds")


# ---------------------------------------------------------------------------
# Figure 2 — Forgetting heat-maps (split into two files, one per algorithm)
# ---------------------------------------------------------------------------

def _plot_fig2_for(data: dict, algo: str, out_dir: Path, suffix: str) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(7.4, 3.4))
    cmap = plt.cm.RdYlGn
    norm = plt.Normalize(0, 100)

    for ax, ds in zip(axes, ["EMNIST-Letters", "CIFAR100"]):
        if algo not in data[ds]:
            ax.set_visible(False)
            continue
        info = data[ds][algo]
        n = info["n_tasks"]
        raw = info["per_task_acc_matrix"]
        mat = np.full((n, n), np.nan, dtype=float)
        for t, row in enumerate(raw):
            for j, v in enumerate(row):
                mat[t, j] = v

        disp = np.ma.array(mat, mask=np.isnan(mat))
        ax.imshow(disp, cmap=cmap, norm=norm, aspect="equal")

        for t in range(n):
            for j in range(t + 1):
                if np.isnan(mat[t, j]):
                    continue
                val = mat[t, j]
                txt_color = "black" if 25 < val < 75 else "white"
                ax.text(j, t, f"{val:.0f}", ha="center", va="center",
                        fontsize=7.5, color=txt_color)

        ax.set_xticks(range(n))
        ax.set_yticks(range(n))
        ax.set_xticklabels([f"T{i+1}" for i in range(n)])
        ax.set_yticklabels([f"after T{i+1}" for i in range(n)])
        ax.tick_params(length=0, top=False, right=False)
        ax.set_xlabel("Test task")
        ax.set_ylabel("Training stage")
        for s in ax.spines.values():
            s.set_visible(False)

    sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=axes.ravel().tolist(),
                        fraction=0.025, pad=0.02, shrink=0.85)
    cbar.set_label("Accuracy (%)")
    save(fig, out_dir, f"fig2_forgetting_heatmap_{suffix}")


def plot_fig2(data_dir: Path, out_dir: Path) -> None:
    data = load(data_dir, "fig2_forgetting_staircase.json")
    _plot_fig2_for(data, "CollEdge", out_dir, "colledge")
    _plot_fig2_for(data, "FedAvg",   out_dir, "fedavg")


# ---------------------------------------------------------------------------
# Figure 3 — Aggregation effect (smaller markers)
# ---------------------------------------------------------------------------

def plot_fig3(data_dir: Path, out_dir: Path) -> None:
    data = load(data_dir, "fig3_aggregation_effect.json")
    fig, axes = plt.subplots(1, 2, figsize=(7.4, 3.0))

    for ax, ds in zip(axes, ["EMNIST-Letters", "CIFAR100"]):
        for algo, info in data[ds].items():
            name = info["display_name"]
            if name in _EXCLUDE:
                continue
            sty = style_for(name)
            n = len(info["rounds"])
            mevery = max(1, n // 14)
            ax.plot(info["rounds"], info["accuracy"], label=name,
                    linewidth=2.0 if name == "CollEdge" else 1.1,
                    markersize=2.8, markevery=mevery,
                    markerfacecolor="white", markeredgewidth=0.8,
                    zorder=10 if name == "CollEdge" else 4, **sty)
        ax.set_title(DS_TITLES[ds])
        ax.set_xlabel("Communication round")
        ax.set_ylabel("Average accuracy (%)" if ax is axes[0] else "")
        ax.tick_params(top=False, right=False)

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=4,
               frameon=False, bbox_to_anchor=(0.5, -0.04))
    fig.tight_layout(rect=[0, 0.05, 1, 1])
    save(fig, out_dir, "fig3_aggregation_effect")


# ---------------------------------------------------------------------------
# Figure 4 — Final per-task accuracy (CollEdge vs DCFCL only)
# ---------------------------------------------------------------------------

def plot_fig4(data_dir: Path, out_dir: Path) -> None:
    data = load(data_dir, "fig4_emergence.json")
    algos = ["CollEdge", "DCFCL"]
    fig, axes = plt.subplots(1, 2, figsize=(7.4, 3.0))

    bw = 0.38
    for ax, ds in zip(axes, ["EMNIST-Letters", "CIFAR100"]):
        n = data[ds][algos[0]]["n_tasks"]
        x = np.arange(n)
        for i, algo in enumerate(algos):
            if algo not in data[ds]:
                continue
            vals = data[ds][algo]["final_per_task_acc"]
            offset = (i - 0.5) * bw
            ax.bar(x + offset, vals, bw,
                   label=algo, color=PALETTE.get(algo),
                   edgecolor="white", linewidth=0.5)
        ax.set_xticks(x)
        ax.set_xticklabels([f"T{i+1}" for i in range(n)])
        ax.set_xlabel("Task index")
        ax.set_ylabel("Accuracy (%) at final round" if ax is axes[0] else "")
        ax.set_title(DS_TITLES[ds])
        ax.set_ylim(0, 100)
        ax.tick_params(top=False, right=False)

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=2,
               frameon=False, bbox_to_anchor=(0.5, -0.04))
    fig.tight_layout(rect=[0, 0.05, 1, 1])
    save(fig, out_dir, "fig4_emergence")


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

REGISTRY = {
    "fig1": plot_fig1,
    "fig2": plot_fig2,
    "fig3": plot_fig3,
    "fig4": plot_fig4,
}


def main(argv: Iterable[str] | None = None) -> None:
    here = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", default=here / "figure_data",
                        type=Path, help="Directory with figureN.json files.")
    parser.add_argument("--out-dir",  default=here / "figures",
                        type=Path, help="Directory in which PDFs/PNGs are written.")
    parser.add_argument("--only", default="", type=str,
                        help="Comma-separated subset, e.g. 'fig1,fig4'.")
    args = parser.parse_args(argv)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    apply_style()

    selected = [s.strip() for s in args.only.split(",") if s.strip()] or list(REGISTRY)
    for key in selected:
        if key not in REGISTRY:
            raise SystemExit(f"unknown figure: {key}")
        REGISTRY[key](args.data_dir, args.out_dir)

    print(f"\nDone. Output → {args.out_dir}")


if __name__ == "__main__":
    main()
