#!/usr/bin/env python3
"""
Publication-grade plotting for the CollEdge paper.

Each figure is generated by an independent function that:
  1. Loads its own JSON file from --data-dir.
  2. Writes a self-contained PDF + PNG to --out-dir.
  3. Shares only a small `apply_style()` rcParams preset with the others.

This file can be copied verbatim into another folder; pass --data-dir to point
at the figure_data/ directory and --out-dir at the desired output location.

Usage
-----
    python plot_figures.py                   # use defaults next to this script
    python plot_figures.py --data-dir DIR --out-dir DIR
    python plot_figures.py --only fig1,fig4  # render a subset
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Iterable

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# ---------------------------------------------------------------------------
# Style
# ---------------------------------------------------------------------------

# Restrained, colour-blind friendly palette inspired by Tableau / ColorBrewer.
PALETTE = {
    "CollEdge":         "#d62728",   # red — our method, used sparingly
    "DCFCL":            "#9467bd",   # purple
    "FedAvg":           "#1f77b4",   # blue
    "FedProx":          "#17becf",   # teal
    "FedLwF":           "#2ca02c",   # green
    "SCAFFOLD":         "#bcbd22",   # olive
    "Per-FedAvg":       "#ff7f0e",   # orange
    "PerAvg":           "#ff7f0e",
    "pFedMe":           "#8c564b",   # brown
    "ClusterFL":        "#e377c2",   # pink
    "Local Only":       "#7f7f7f",   # grey
    "Local":            "#7f7f7f",
    # Ablation variants
    "DCFCL (Baseline)": "#7f7f7f",
    "+DER++":           "#1f77b4",
    "+DER++ +Directed": "#2ca02c",
    "+DER++ +Coalition":"#ff7f0e",
    "Directed only":    "#9467bd",
    "Coalition only":   "#17becf",
}

LINESTYLES = {
    "CollEdge":   "-",
    "DCFCL":      "--",
    "FedAvg":     "-",
    "FedProx":    "-.",
    "FedLwF":     ":",
    "SCAFFOLD":   "--",
    "Per-FedAvg": "-.",
    "PerAvg":     "-.",
    "pFedMe":     ":",
    "ClusterFL":  "--",
    "Local Only": ":",
    "Local":      ":",
}

MARKERS = {
    "CollEdge":   "o",
    "DCFCL":      "s",
    "FedAvg":     "^",
    "FedProx":    "D",
    "FedLwF":     "v",
    "SCAFFOLD":   "P",
    "Per-FedAvg": "*",
    "PerAvg":     "*",
    "pFedMe":     "X",
    "ClusterFL":  "h",
    "Local Only": "x",
    "Local":      "x",
}

DS_TITLES = {
    "EMNIST-Letters": "EMNIST-Letters",
    "CIFAR100":       "CIFAR-100",
}


# ---------------------------------------------------------------------------
# Unified font sizes for ALL figures (override per-figure where noted).
# Chosen so that figure title / axis label / tick label / legend stay
# visually consistent across heat-maps, line plots, polar plots, etc.
# ---------------------------------------------------------------------------
FONT_BASE        = 9.0
FONT_TITLE       = 10.0
FONT_AXIS_LABEL  = 9.0
FONT_TICK        = 8.0
FONT_LEGEND      = 8.0


def apply_style(*, base: float = FONT_BASE, title: float = FONT_TITLE,
                axis_label: float = FONT_AXIS_LABEL, tick: float = FONT_TICK,
                legend: float = FONT_LEGEND) -> None:
    """Single-source rcParams preset (Arial, Nature-style)."""
    plt.rcParams.update(
        {
            # Fonts — Arial everywhere
            "font.family":      "sans-serif",
            "font.sans-serif":  ["Arial", "Helvetica", "DejaVu Sans"],
            "mathtext.fontset": "custom",
            "mathtext.rm":      "Arial",
            "mathtext.it":      "Arial:italic",
            "mathtext.bf":      "Arial:bold",
            "font.size":        base,
            "axes.titlesize":   title,
            "axes.labelsize":   axis_label,
            "xtick.labelsize":  tick,
            "ytick.labelsize":  tick,
            "legend.fontsize":  legend,
            "legend.title_fontsize": legend,
            # Lines / spines (Nature-like: thin, no top/right)
            "axes.linewidth":   0.9,
            "lines.linewidth":  1.5,
            "axes.spines.top":   False,
            "axes.spines.right": False,
            "xtick.major.width": 0.9,
            "ytick.major.width": 0.9,
            "xtick.direction":  "out",
            "ytick.direction":  "out",
            "xtick.major.size": 3.0,
            "ytick.major.size": 3.0,
            # Grid (light, only y by default)
            "axes.grid":        False,
            "grid.alpha":       0.25,
            "grid.linestyle":   "-",
            "grid.linewidth":   0.4,
            # Output
            "figure.dpi":       150,
            "savefig.dpi":      300,
            "savefig.bbox":     "tight",
            "pdf.fonttype":     42,
            "ps.fonttype":      42,
        }
    )


def style_for(name: str) -> dict:
    return dict(
        color=PALETTE.get(name, "#444444"),
        linestyle=LINESTYLES.get(name, "-"),
        marker=MARKERS.get(name, "."),
    )


# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------

def load(data_dir: Path, fname: str) -> dict:
    with open(data_dir / fname, "r") as f:
        return json.load(f)


def save(fig, out_dir: Path, name: str) -> None:
    pdf = out_dir / f"{name}.pdf"
    png = out_dir / f"{name}.png"
    fig.savefig(pdf)
    fig.savefig(png)
    plt.close(fig)
    print(f"[ok] {pdf.relative_to(pdf.parents[1])}")


# ---------------------------------------------------------------------------
# Figure 2 — Forgetting heat-maps (per dataset, 1x3 algorithm panels)
# ---------------------------------------------------------------------------

# Algorithms excluded from per-round figures (Per-FedAvg removed by request).
_EXCLUDE = {"PerAvg", "Per-FedAvg"}

# Algorithm comparison set used for the forgetting heat-maps and the
# emergence figure. Order is left-to-right / column order in those panels.
_F2_ALGOS = ["FedAvg", "DCFCL", "CollEdge"]


def _plot_fig2_for_dataset(data: dict, ds: str, out_dir: Path, suffix: str) -> None:
    """One PDF per dataset: 1x3 panels comparing FedAvg / DCFCL / CollEdge."""
    fig, axes = plt.subplots(1, 3, figsize=(8.6, 3.2))
    cmap = plt.cm.RdYlGn
    norm = plt.Normalize(0, 100)

    for ax, algo in zip(axes, _F2_ALGOS):
        if algo not in data[ds]:
            ax.set_visible(False)
            continue
        info = data[ds][algo]
        n = info["n_tasks"]
        raw = info["per_task_acc_matrix"]
        mat = np.full((n, n), np.nan, dtype=float)
        for t, row in enumerate(raw):
            for j, v in enumerate(row):
                mat[t, j] = v

        disp = np.ma.array(mat, mask=np.isnan(mat))
        ax.imshow(disp, cmap=cmap, norm=norm, aspect="equal")

        # Smaller cell labels for the 10x10 CIFAR grid.
        cell_fs = 6.5 if n <= 6 else 5.5
        for t in range(n):
            for j in range(t + 1):
                if np.isnan(mat[t, j]):
                    continue
                val = mat[t, j]
                txt_color = "black" if 25 < val < 75 else "white"
                ax.text(j, t, f"{val:.0f}", ha="center", va="center",
                        fontsize=cell_fs, color=txt_color)

        ax.set_xticks(range(n))
        ax.set_yticks(range(n))
        ax.set_xticklabels([f"T{i+1}" for i in range(n)])
        ax.set_yticklabels([f"after T{i+1}" for i in range(n)])
        ax.tick_params(length=0, top=False, right=False)
        ax.set_xlabel("Test task")
        if ax is axes[0]:
            ax.set_ylabel("Training stage")
        ax.set_title(info["display_name"], pad=4)
        for s in ax.spines.values():
            s.set_visible(False)

    sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=axes.ravel().tolist(),
                        fraction=0.020, pad=0.02, shrink=0.85)
    cbar.set_label("Accuracy (%)")
    save(fig, out_dir, f"forgetting_heatmap_{suffix}")


def plot_fig2(data_dir: Path, out_dir: Path) -> None:
    data = load(data_dir, "fig2_forgetting_staircase.json")
    _plot_fig2_for_dataset(data, "EMNIST-Letters", out_dir, "emnist")
    _plot_fig2_for_dataset(data, "CIFAR100",       out_dir, "cifar100")


# ---------------------------------------------------------------------------
# Figure 3 — Accuracy vs communication round (1x2, all baselines)
#
# Merges the previous Fig.~1 (per-round trajectories of every baseline) with
# the previous Fig.~3 (aggregation-effect curves), since they conveyed the
# same information. Uses the richer fig1_comm_rounds.json source.
# ---------------------------------------------------------------------------

def plot_fig3(data_dir: Path, out_dir: Path) -> None:
    data = load(data_dir, "fig1_comm_rounds.json")
    # Smaller fonts dedicated to this figure (request: shrink for clarity).
    apply_style(base=7.5, title=8.5, axis_label=8.0, tick=7.0, legend=7.0)
    fig, axes = plt.subplots(1, 2, figsize=(7.4, 3.0))

    panel_labels = ["a", "b"]
    for ax, ds, plab in zip(axes, ["EMNIST-Letters", "CIFAR100"], panel_labels):
        for algo, info in data[ds].items():
            name = info["display_name"]
            if name in _EXCLUDE:
                continue
            sty = style_for(name)
            n = len(info["rounds"])
            mevery = max(1, n // 12)
            ax.plot(
                info["rounds"], info["accuracy"],
                label=name,
                linewidth=1.7 if name == "CollEdge" else 1.0,
                markersize=2.6, markevery=mevery,
                markerfacecolor="white", markeredgewidth=0.7,
                zorder=10 if name == "CollEdge" else 4,
                **sty,
            )
        # Task-boundary guides
        n_rounds = len(next(iter(data[ds].values()))["rounds"])
        n_tasks = 6 if ds == "EMNIST-Letters" else 10
        for t in range(1, n_tasks):
            ax.axvline(t * n_rounds // n_tasks, color="0.75",
                       linestyle=":", linewidth=0.5, zorder=1)
        ax.set_title(DS_TITLES[ds], pad=3)
        ax.set_xlabel("Communication round")
        ax.set_ylabel("Average accuracy (%)" if ax is axes[0] else "")
        ax.text(-0.10, 1.02, plab, transform=ax.transAxes,
                fontsize=8.5, fontweight="bold", va="bottom", ha="right")
        ax.margins(x=0.01)
        ax.tick_params(top=False, right=False)

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=4,
               frameon=False, bbox_to_anchor=(0.5, -0.05))
    fig.tight_layout(rect=[0, 0.07, 1, 1])
    save(fig, out_dir, "accuracy_vs_round")
    # Restore unified style for any subsequent figure.
    apply_style()


# ---------------------------------------------------------------------------
# Figure 4 — Emergence: per-task accuracy trajectories (Nature-style)
#
# 2 (rows: datasets) x 3 (cols: FedAvg / DCFCL / CollEdge) small-multiples.
# Each panel plots, for every task index j (encoded by a viridis colour),
# the test accuracy on task j as the model progresses through training
# stages t=j..n-1. A high, sustained line on a task index j << t indicates
# that the federation continues to perform well on a task whose data the
# typical client has not seen for many stages, i.e. the emergence effect.
# ---------------------------------------------------------------------------

# Local, Nature-style trio used only inside plot_fig4 to avoid affecting
# the global PALETTE shared by the other figures.
_F4_ALGOS = ["FedAvg", "DCFCL", "CollEdge"]


def plot_fig4(data_dir: Path, out_dir: Path) -> None:
    data = load(data_dir, "fig4_emergence.json")
    datasets = ["EMNIST-Letters", "CIFAR100"]

    # Build flat 1x6 panel list: (dataset, algorithm) for each column.
    panels = [(ds, alg) for ds in datasets for alg in _F4_ALGOS
              if alg in data[ds]]
    n_panels = len(panels)

    fig, axes = plt.subplots(1, n_panels, figsize=(2.05 * n_panels, 2.6),
                             sharex=False, sharey=True)
    if n_panels == 1:
        axes = np.array([axes])

    cmap = plt.cm.viridis
    n_max = max(data[ds][alg]["n_tasks"] for ds, alg in panels)

    for c, (ds, algo) in enumerate(panels):
        ax = axes[c]
        info = data[ds][algo]
        n = info["n_tasks"]
        task_colors = [cmap(0.05 + 0.9 * (j / max(1, n - 1))) for j in range(n)]
        stages = np.arange(1, n + 1)
        mat = info["per_task_acc_matrix"]
        for j in range(n):
            xs = list(range(j + 1, n + 1))
            ys = [mat[t][j] for t in range(j, n)]
            ax.plot(xs, ys,
                    color=task_colors[j],
                    linewidth=1.3,
                    marker="o", markersize=2.5,
                    markeredgecolor=task_colors[j],
                    markerfacecolor="white", markeredgewidth=0.7,
                    zorder=4)

        ax.set_xticks(stages)
        ax.set_xticklabels([f"T{int(s)}" for s in stages],
                           rotation=0 if n <= 6 else 45, ha="center")
        ax.set_xlim(0.5, n + 0.5)
        ax.set_ylim(0, 100)
        ax.tick_params(top=False, right=False)
        # Two-line title: dataset on top, algorithm beneath.
        ax.set_title(f"{DS_TITLES[ds]}\n{info['display_name']}", pad=4)
        ax.set_xlabel("Training stage")
        if c == 0:
            ax.set_ylabel("Accuracy (%)")

    # Shared task-index colourbar on the right.
    sm = plt.cm.ScalarMappable(cmap=cmap, norm=plt.Normalize(1, n_max))
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=axes.ravel().tolist(),
                        fraction=0.012, pad=0.015, shrink=0.85,
                        ticks=np.arange(1, n_max + 1))
    cbar.set_label("Task index $j$ (older $\\rightarrow$ newer)")
    cbar.ax.set_yticklabels([f"T{int(t)}" for t in np.arange(1, n_max + 1)])

    save(fig, out_dir, "emergence_trajectories")


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

REGISTRY = {
    "fig2": plot_fig2,
    "fig3": plot_fig3,
    "fig4": plot_fig4,
}


def main(argv: Iterable[str] | None = None) -> None:
    here = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", default=here / "figure_data",
                        type=Path, help="Directory with figureN.json files.")
    parser.add_argument("--out-dir",  default=here / "figures",
                        type=Path, help="Directory in which PDFs/PNGs are written.")
    parser.add_argument("--only", default="", type=str,
                        help="Comma-separated subset, e.g. 'fig1,fig4'.")
    args = parser.parse_args(argv)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    apply_style()

    selected = [s.strip() for s in args.only.split(",") if s.strip()] or list(REGISTRY)
    for key in selected:
        if key not in REGISTRY:
            raise SystemExit(f"unknown figure: {key}")
        REGISTRY[key](args.data_dir, args.out_dir)

    print(f"\nDone. Output → {args.out_dir}")


if __name__ == "__main__":
    main()
